//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiLocation
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLocation()
        {
            this.tblPaiments = new HashSet<tblPaiment>();
        }
    
        public int IDLocation { get; set; }
        public Nullable<System.DateTime> DateDebutLocation { get; set; }
        public Nullable<System.DateTime> DatePremierPaiment { get; set; }
        public Nullable<decimal> MontantPaimentMensuel { get; set; }
        public Nullable<int> NombrePaimentMensuel { get; set; }
        public string NIVVehicule { get; set; }
        public int IDClient { get; set; }
        public int IDTerme { get; set; }
    
        public virtual tblClient tblClient { get; set; }
        public virtual tblTerme tblTerme { get; set; }
        public virtual tblVehicule tblVehicule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPaiment> tblPaiments { get; set; }
    }
}
